FROM python:3.9

WORKDIR /app
# ADD . .

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Important Install For GDAL
RUN apt-get update \
  && apt-get install -y gdal-bin libgdal-dev

RUN export CPLUS_INCLUDE_PATH=/usr/include/gdal
RUN export C_INCLUDE_PATH=/usr/include/gdal

# Install requirements
COPY ./server/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Add source code

# Set environment variables
ENV FLASK_APP=server/app.py

# Run
ENTRYPOINT [ "flask", "run", "--host=0.0.0.0" ]