# -*- coding: utf-8 -*-
"""v1_0_2

- remove unused columns from project table
- change rectangle and polygon coords from center origin to upper left origin

Revision ID: a53874071f6e
Revises: e660f34b820d
Create Date: 2023-02-08 23:23:59.709127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a53874071f6e"
down_revision = "e660f34b820d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project") as batch_op:
        batch_op.drop_column("label_format")
        batch_op.drop_column("label_dir")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("label_dir", sa.VARCHAR(), nullable=True))
    op.add_column("project", sa.Column("label_format", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
