# -*- coding: utf-8 -*-
"""v1.0.1
- reset sample folder

Revision ID: e660f34b820d
Revises: f47b7f5b73b9
Create Date: 2023-01-24 06:35:13.150458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e660f34b820d"
down_revision = "f47b7f5b73b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from paddlelabel.api.controller.sample import reset_samples

    reset_samples()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
