"""v0.5.0 Make sure the size of all tasks are 1,h,w

Revision ID: f47b7f5b73b9
Revises: a609821ce310
Create Date: 2023-01-09 18:31:50.399688

"""
from pathlib import Path

from alembic import op
import sqlalchemy as sa
import cv2
import os.path as osp
from PIL import Image

from paddlelabel.api.model import Project, Task
from paddlelabel.config import se

# revision identifiers, used by Alembic.
revision = "f47b7f5b73b9"
down_revision = "a609821ce310"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    projects = Project.query.all()
    pjid2data_dir = {p.project_id: Path(p.data_dir) for p in projects}

    tasks = Task.query.all()
    for task in tasks:
        data = task.datas[0]
        img_path = osp.join(pjid2data_dir[task.project_id], data.path)
        im = Image.open(img_path)
        s = ",".join(map(str, (1,) + (im.size[::-1])))
        data.size = s
    se.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
