name: Publish doc to pages

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      force_regen:
        description: "Force the jekyll generation step"
        required: false
        default: true
        type: boolean


jobs:
  publish_doc:
    uses: PaddleCV-SIG/PaddleLabel/.github/workflows/doc_to_pages.yml@develop
    with:
      baseurl: "/PaddleLabel/"
      deploy: true
      force_regen: ${{ inputs.force_regen }}
